# Generated by Django 5.0.7 on 2024-07-16 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacaoWeber', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tarefa',
        ),
    ]
