# Generated by Django 5.0.7 on 2024-07-23 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autenticacaoWeber', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('incomum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='loj_codigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incomum.loja'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
