# Generated by Django 5.0.7 on 2024-07-23 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacaoWeber', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
    ]
