# Generated by Django 5.0.7 on 2024-07-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacaoWeber', '0004_alter_usuario_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
