# Generated by Django 5.0.7 on 2024-07-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacaoWeber', '0005_alter_usuario_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='ven_codigo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='cid_codigo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ven_bairro',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ven_celular',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ven_cep',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ven_endereco',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ven_fone',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ven_numero',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ven_observacao',
            field=models.CharField(blank=True, max_length=170, null=True),
        ),
    ]
