# Generated by Django 5.0.7 on 2024-07-30 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacaoWeber', '0006_remove_usuario_ven_codigo_usuario_cid_codigo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='loj_codigo',
        ),
    ]
