# Generated by Django 5.0.7 on 2024-07-16 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaComercial',
            fields=[
                ('aco_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('aco_descricao', models.CharField(blank=True, max_length=50, null=True)),
                ('aco_datacadastro', models.DateTimeField(blank=True, null=True)),
                ('aco_situacao', models.IntegerField(blank=True, null=True)),
                ('aco_rateio', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Áreas Comerciais',
                'db_table': 'areacomercial',
            },
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('loj_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('loj_descricao', models.CharField(blank=True, max_length=50, null=True)),
                ('loj_responsavel', models.CharField(blank=True, max_length=30, null=True)),
                ('loj_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('loj_endereco', models.CharField(blank=True, max_length=80, null=True)),
                ('loj_bairro', models.CharField(blank=True, max_length=45, null=True)),
                ('cep_codigo', models.IntegerField(blank=True, null=True)),
                ('cid_codigo', models.IntegerField(blank=True, null=True)),
                ('loj_fone', models.CharField(blank=True, max_length=20, null=True)),
                ('loj_fax', models.CharField(blank=True, max_length=20, null=True)),
                ('loj_emailloja', models.EmailField(blank=True, max_length=50, null=True)),
                ('loj_homepage', models.URLField(blank=True, max_length=50, null=True)),
                ('loj_emailfinanceiro', models.EmailField(blank=True, max_length=60, null=True)),
                ('loj_textorelatorio', models.CharField(blank=True, max_length=40, null=True)),
                ('loj_cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('loj_serie', models.IntegerField(blank=True, null=True)),
                ('loj_codigoempresa', models.IntegerField(blank=True, null=True)),
                ('loj_emailbloqueio', models.EmailField(blank=True, max_length=60, null=True)),
                ('loj_situacao', models.IntegerField(blank=True, null=True)),
                ('loj_codigofinanceiro', models.IntegerField(blank=True, null=True)),
                ('aco_codigo', models.IntegerField(blank=True, null=True)),
                ('loj_vendacorte', models.IntegerField(blank=True, null=True)),
                ('loj_contrato', models.IntegerField(blank=True, null=True)),
                ('loj_cortevendedor', models.IntegerField(blank=True, null=True)),
                ('nem_codigo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Lojas',
                'db_table': 'public.loja',
            },
        ),
        migrations.CreateModel(
            name='Loja_AreaComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'viagem.lojacomercial',
            },
        ),
        migrations.AddConstraint(
            model_name='areacomercial',
            constraint=models.UniqueConstraint(fields=('aco_codigo',), name='pk_areacomercial'),
        ),
        migrations.AddConstraint(
            model_name='loja',
            constraint=models.UniqueConstraint(fields=('loj_codigo',), name='pk_loja'),
        ),
        migrations.AddField(
            model_name='loja_areacomercial',
            name='aco_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incomum.areacomercial'),
        ),
        migrations.AddField(
            model_name='loja_areacomercial',
            name='loj_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incomum.loja'),
        ),
        migrations.AddConstraint(
            model_name='loja_areacomercial',
            constraint=models.UniqueConstraint(fields=('loj_codigo', 'aco_codigo'), name='pk_lojacomercial'),
        ),
    ]
