# Generated by Django 5.0.7 on 2024-08-12 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('age_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('age_descricao', models.CharField(blank=True, max_length=70, null=True)),
                ('age_endereco', models.CharField(blank=True, max_length=60, null=True)),
                ('age_numero', models.CharField(blank=True, max_length=20, null=True)),
                ('age_bairro', models.CharField(blank=True, max_length=35, null=True)),
                ('age_cep', models.IntegerField(blank=True, null=True)),
                ('cid_codigo', models.IntegerField(blank=True, null=True)),
                ('age_fone', models.CharField(blank=True, max_length=20, null=True)),
                ('age_celular', models.CharField(blank=True, max_length=20, null=True)),
                ('age_observacao', models.CharField(blank=True, max_length=180, null=True)),
                ('age_dataatualizacao', models.DateTimeField(blank=True, null=True)),
                ('age_datacadastro', models.DateTimeField(blank=True, null=True)),
                ('ban_codigo', models.IntegerField(blank=True, null=True)),
                ('age_agencia', models.CharField(blank=True, max_length=5, null=True)),
                ('age_contacorrente', models.CharField(blank=True, max_length=15, null=True)),
                ('age_complementar', models.CharField(blank=True, max_length=1, null=True)),
                ('age_codigocontabil', models.IntegerField(blank=True, null=True)),
                ('age_cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('age_situacao', models.CharField(blank=True, max_length=1, null=True)),
                ('age_comissao', models.FloatField(blank=True, null=True)),
                ('age_over', models.FloatField(blank=True, null=True)),
                ('par_codigo', models.IntegerField(blank=True, null=True)),
                ('age_imagem', models.BinaryField(blank=True, null=True)),
                ('age_descricaosite', models.CharField(blank=True, max_length=70, null=True)),
                ('age_verificar', models.CharField(blank=True, max_length=1, null=True)),
                ('age_inscricaomunicipal', models.CharField(blank=True, max_length=20, null=True)),
                ('age_markup', models.FloatField(blank=True, null=True)),
                ('aco_codigo', models.IntegerField(blank=True, null=True)),
                ('age_markupliberado', models.FloatField(blank=True, null=True)),
                ('age_codigoprincipal', models.IntegerField(blank=True, null=True)),
                ('age_codigoimportacao', models.IntegerField(blank=True, null=True)),
                ('age_razaosocial', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'verbose_name': 'Agencia',
                'verbose_name_plural': 'Agencias',
                'db_table': 'agencia',
            },
        ),
        migrations.CreateModel(
            name='AreaComercial',
            fields=[
                ('aco_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('aco_descricao', models.CharField(blank=True, max_length=50, null=True)),
                ('aco_datacadastro', models.DateTimeField(auto_now_add=True, null=True)),
                ('aco_situacao', models.IntegerField(blank=True, null=True)),
                ('aco_rateio', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Áreas Comerciais',
                'db_table': 'areacomercial',
            },
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('loj_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('loj_descricao', models.CharField(blank=True, max_length=50, null=True)),
                ('loj_responsavel', models.CharField(blank=True, max_length=30, null=True)),
                ('loj_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('loj_endereco', models.CharField(blank=True, max_length=80, null=True)),
                ('loj_bairro', models.CharField(blank=True, max_length=45, null=True)),
                ('cep_codigo', models.IntegerField(blank=True, null=True)),
                ('cid_codigo', models.IntegerField(blank=True, null=True)),
                ('loj_fone', models.CharField(blank=True, max_length=20, null=True)),
                ('loj_fax', models.CharField(blank=True, max_length=20, null=True)),
                ('loj_emailloja', models.EmailField(blank=True, max_length=50, null=True)),
                ('loj_emailfinanceiro', models.EmailField(blank=True, max_length=60, null=True)),
                ('loj_textorelatorio', models.CharField(blank=True, max_length=40, null=True)),
                ('loj_cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('loj_serie', models.IntegerField(blank=True, null=True)),
                ('loj_codigoempresa', models.IntegerField(blank=True, null=True)),
                ('loj_emailbloqueio', models.EmailField(blank=True, max_length=60, null=True)),
                ('loj_situacao', models.IntegerField(blank=True, null=True)),
                ('loj_codigofinanceiro', models.IntegerField(blank=True, null=True)),
                ('loj_vendacorte', models.IntegerField(blank=True, null=True)),
                ('loj_contrato', models.IntegerField(blank=True, null=True)),
                ('loj_cortevendedor', models.IntegerField(blank=True, null=True)),
                ('nem_codigo', models.IntegerField(blank=True, null=True)),
                ('aco_codigo', models.ForeignKey(blank=True, db_column='aco_codigo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='incomum.areacomercial')),
            ],
            options={
                'verbose_name_plural': 'Lojas',
                'db_table': 'loja',
            },
        ),
        migrations.AddField(
            model_name='areacomercial',
            name='loja_codigo',
            field=models.ForeignKey(db_column='loj_codigo', on_delete=django.db.models.deletion.DO_NOTHING, related_name='areaComercial', to='incomum.loja'),
        ),
        migrations.CreateModel(
            name='UsuarioAreaComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_comercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incomum.areacomercial')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario_areacomercial',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('ven_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('ban_codigo', models.IntegerField(blank=True, null=True)),
                ('ven_agencia', models.CharField(blank=True, max_length=7, null=True)),
                ('ven_contacorrente', models.CharField(blank=True, max_length=15, null=True)),
                ('ven_descricaoweb1', models.CharField(blank=True, max_length=60, null=True)),
                ('ven_descricaoweb2', models.CharField(blank=True, max_length=60, null=True)),
                ('ven_codigoimportacao', models.IntegerField(blank=True, null=True)),
                ('usr_codigo', models.ForeignKey(blank=True, db_column='usr_codigo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'db_table': 'vendedor',
            },
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('fim_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('tur_codigo', models.IntegerField()),
                ('fim_data', models.DateField()),
                ('fim_tipo', models.CharField(max_length=10)),
                ('tur_numerovenda', models.CharField(max_length=20)),
                ('fim_valorliquido', models.FloatField()),
                ('fim_markup', models.FloatField()),
                ('fim_valorinc', models.FloatField()),
                ('fim_valorincajustado', models.FloatField()),
                ('aco_codigo', models.ForeignKey(blank=True, db_column='aco_codigo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='incomum.areacomercial')),
                ('age_codigo', models.ForeignKey(blank=True, db_column='age_codigo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='incomum.agencia')),
                ('loj_codigo', models.ForeignKey(blank=True, db_column='loj_codigo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='incomum.loja')),
                ('ven_codigo', models.ForeignKey(blank=True, db_column='ven_codigo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='incomum.vendedor')),
            ],
            options={
                'verbose_name': 'Faturamento Simplificado',
                'verbose_name_plural': 'Faturamentos Simplificados',
                'db_table': 'faturamentosimplificado',
            },
        ),
        migrations.AddConstraint(
            model_name='loja',
            constraint=models.UniqueConstraint(fields=('loj_codigo',), name='pk_loja'),
        ),
        migrations.AddConstraint(
            model_name='areacomercial',
            constraint=models.UniqueConstraint(fields=('aco_codigo',), name='pk_areacomercial'),
        ),
        migrations.AlterUniqueTogether(
            name='usuarioareacomercial',
            unique_together={('usuario', 'area_comercial')},
        ),
    ]
