# Generated by Django 5.0.7 on 2024-08-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='ven_descricao',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
