# Generated by Django 5.0.7 on 2024-07-16 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incomum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loja',
            table='loja',
        ),
        migrations.AlterModelTable(
            name='loja_areacomercial',
            table='lojacomercial',
        ),
    ]
