# Generated by Django 5.0.7 on 2024-08-02 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomum', '0002_remove_loja_loj_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaturamentoSimplificado',
            fields=[
                ('fim_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('tur_codigo', models.IntegerField()),
                ('fim_data', models.DateField()),
                ('fim_tipo', models.CharField(max_length=10)),
                ('tur_numerovenda', models.CharField(max_length=20)),
                ('fim_valorliquido', models.FloatField()),
                ('fim_markup', models.FloatField()),
                ('fim_valorinc', models.FloatField()),
                ('fim_valorincajustado', models.FloatField()),
                ('aco_codigo', models.ForeignKey(blank=True, db_column='aco_codigo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='incomum.areacomercial')),
                ('loj_codigo', models.ForeignKey(blank=True, db_column='loj_codigo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='incomum.loja')),
            ],
            options={
                'verbose_name': 'Faturamento Simplificado',
                'verbose_name_plural': 'Faturamentos Simplificados',
                'db_table': 'faturamentosimplificado',
            },
        ),
    ]
