# Generated by Django 5.0.7 on 2024-08-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomum', '0002_vendedor_ven_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencia',
            name='age_descricao',
            field=models.CharField(max_length=70),
        ),
    ]
