# Generated by Django 5.0.7 on 2024-07-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomum', '0002_remove_loja_loj_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaturamentoSimplificado',
            fields=[
                ('fim_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('tur_codigo', models.IntegerField()),
                ('loj_codigo', models.IntegerField()),
                ('ven_codigo', models.IntegerField()),
                ('age_codigo', models.IntegerField()),
                ('fim_data', models.DateField()),
                ('aco_codigo', models.IntegerField()),
                ('fim_tipo', models.CharField(max_length=10)),
                ('tur_numerovenda', models.CharField(max_length=20)),
                ('fim_valorliquido', models.FloatField()),
                ('fim_markup', models.FloatField()),
                ('fim_valorinc', models.FloatField()),
                ('fim_valorincajustado', models.FloatField()),
                ('loj_descricao', models.CharField(max_length=10)),
                ('aco_descricao', models.CharField(max_length=20)),
                ('ven_descricao', models.CharField(max_length=40)),
                ('age_descricao', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Faturamento Simplificado',
                'verbose_name_plural': 'Faturamentos Simplificados',
                'db_table': 'faturamentosimplificado',
            },
        ),
    ]
