# Generated by Django 5.0.7 on 2024-07-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomum', '0002_alter_loja_table_alter_loja_areacomercial_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areacomercial',
            name='aco_datacadastro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
