# Generated by Django 5.0.7 on 2024-07-16 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomum', '0003_alter_areacomercial_aco_datacadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacomercial',
            name='loja_codigo',
            field=models.ForeignKey(db_column='loj_codigo', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='areaComercial', to='incomum.loja'),
        ),
        migrations.DeleteModel(
            name='Loja_AreaComercial',
        ),
    ]
