# Generated by Django 5.0.7 on 2024-08-19 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomum', '0003_alter_agencia_age_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencia',
            name='aco_codigo',
            field=models.ForeignKey(blank=True, db_column='aco_codigo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='incomum.areacomercial'),
        ),
    ]
