# Generated by Django 5.0.7 on 2024-07-30 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incomum', '0003_faturamentosimplificado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faturamentosimplificado',
            name='aco_descricao',
        ),
        migrations.RemoveField(
            model_name='faturamentosimplificado',
            name='age_descricao',
        ),
        migrations.RemoveField(
            model_name='faturamentosimplificado',
            name='loj_descricao',
        ),
        migrations.RemoveField(
            model_name='faturamentosimplificado',
            name='ven_descricao',
        ),
    ]
