# Generated by Django 5.0.7 on 2024-07-16 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomum', '0004_areacomercial_loja_codigo_delete_loja_areacomercial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areacomercial',
            name='loja_codigo',
            field=models.ForeignKey(db_column='loj_codigo', on_delete=django.db.models.deletion.DO_NOTHING, related_name='areaComercial', to='incomum.loja'),
        ),
    ]
