# Generated by Django 5.0.7 on 2024-07-30 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomum', '0004_remove_faturamentosimplificado_aco_descricao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('ven_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('ven_descricao', models.CharField(blank=True, max_length=60, null=True)),
                ('ven_datacadastro', models.DateTimeField(auto_now_add=True, null=True)),
                ('ven_dataatualizacao', models.DateTimeField(blank=True, null=True)),
                ('ven_endereco', models.CharField(blank=True, max_length=60, null=True)),
                ('ven_numero', models.CharField(blank=True, max_length=15, null=True)),
                ('ven_bairro', models.CharField(blank=True, max_length=30, null=True)),
                ('ven_cep', models.IntegerField(blank=True, null=True)),
                ('cid_codigo', models.IntegerField(blank=True, null=True)),
                ('ven_fone', models.CharField(blank=True, max_length=17, null=True)),
                ('ven_celular', models.CharField(blank=True, max_length=17, null=True)),
                ('ven_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('ven_observacao', models.CharField(blank=True, max_length=170, null=True)),
                ('ban_codigo', models.IntegerField(blank=True, null=True)),
                ('ven_agencia', models.CharField(blank=True, max_length=7, null=True)),
                ('ven_contacorrente', models.CharField(blank=True, max_length=15, null=True)),
                ('ven_cpf', models.CharField(blank=True, max_length=20, null=True)),
                ('ven_descricaoauxiliar', models.CharField(blank=True, max_length=60, null=True)),
                ('ven_situacao', models.CharField(blank=True, max_length=1, null=True)),
                ('ven_descricaoweb', models.CharField(blank=True, max_length=60, null=True)),
                ('ven_codigoimportacao', models.IntegerField(blank=True, null=True)),
                ('sve_codigo', models.IntegerField(blank=True, null=True)),
                ('loj_codigo', models.ForeignKey(blank=True, db_column='loj_codigo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='incomum.loja')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'db_table': 'vendedor',
            },
        ),
    ]
