# Generated by Django 5.0.7 on 2024-07-30 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomum', '0005_vendedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendedor',
            old_name='ven_descricaoauxiliar',
            new_name='ven_descricaoweb1',
        ),
        migrations.RenameField(
            model_name='vendedor',
            old_name='ven_descricaoweb',
            new_name='ven_descricaoweb2',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='cid_codigo',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='loj_codigo',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='sve_codigo',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='ven_bairro',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='ven_celular',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='ven_cep',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='ven_cpf',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='ven_dataatualizacao',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='ven_datacadastro',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='ven_descricao',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='ven_email',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='ven_endereco',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='ven_fone',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='ven_numero',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='ven_observacao',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='ven_situacao',
        ),
        migrations.AddField(
            model_name='vendedor',
            name='usr_codigo',
            field=models.ForeignKey(blank=True, db_column='usr_codigo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
