# Generated by Django 5.0.7 on 2024-07-17 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomum', '0005_alter_areacomercial_loja_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='aco_codigo',
            field=models.ForeignKey(blank=True, db_column='aco_codigo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='incomum.areacomercial'),
        ),
    ]
