# Generated by Django 5.0.7 on 2024-07-30 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incomum', '0006_rename_ven_descricaoauxiliar_vendedor_ven_descricaoweb1_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuarioareacomercial',
            table='usuario_areacomercial',
        ),
    ]
