# Generated by Django 5.0.7 on 2024-07-17 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('incomum', '0007_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dep_codigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='loj_codigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incomum.loja'),
        ),
    ]
