# Generated by Django 5.0.7 on 2024-07-30 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomum', '0007_alter_usuarioareacomercial_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faturamentosimplificado',
            name='aco_codigo',
            field=models.ForeignKey(blank=True, db_column='aco_codigo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='incomum.areacomercial'),
        ),
        migrations.AlterField(
            model_name='faturamentosimplificado',
            name='loj_codigo',
            field=models.ForeignKey(blank=True, db_column='loj_codigo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='incomum.loja'),
        ),
        migrations.AlterField(
            model_name='faturamentosimplificado',
            name='ven_codigo',
            field=models.ForeignKey(blank=True, db_column='ven_codigo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='incomum.vendedor'),
        ),
    ]
