# Generated by Django 5.0.7 on 2024-07-17 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomum', '0008_alter_usuario_dep_codigo_alter_usuario_loj_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioAreaComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_comercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incomum.areacomercial')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'area_comercial')},
            },
        ),
    ]
