# Generated by Django 5.0.7 on 2024-07-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomum', '0008_alter_faturamentosimplificado_aco_codigo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('age_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('age_descricao', models.CharField(blank=True, max_length=70, null=True)),
                ('age_endereco', models.CharField(blank=True, max_length=60, null=True)),
                ('age_numero', models.CharField(blank=True, max_length=20, null=True)),
                ('age_bairro', models.CharField(blank=True, max_length=35, null=True)),
                ('age_cep', models.IntegerField(blank=True, null=True)),
                ('cid_codigo', models.IntegerField(blank=True, null=True)),
                ('age_fone', models.CharField(blank=True, max_length=20, null=True)),
                ('age_celular', models.CharField(blank=True, max_length=20, null=True)),
                ('age_observacao', models.CharField(blank=True, max_length=180, null=True)),
                ('age_dataatualizacao', models.DateTimeField(blank=True, null=True)),
                ('age_datacadastro', models.DateTimeField(blank=True, null=True)),
                ('ban_codigo', models.IntegerField(blank=True, null=True)),
                ('age_agencia', models.CharField(blank=True, max_length=5, null=True)),
                ('age_contacorrente', models.CharField(blank=True, max_length=15, null=True)),
                ('age_complementar', models.CharField(blank=True, max_length=1, null=True)),
                ('age_codigocontabil', models.IntegerField(blank=True, null=True)),
                ('age_cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('age_situacao', models.CharField(blank=True, max_length=1, null=True)),
                ('age_comissao', models.FloatField(blank=True, null=True)),
                ('age_over', models.FloatField(blank=True, null=True)),
                ('par_codigo', models.IntegerField(blank=True, null=True)),
                ('age_imagem', models.BinaryField(blank=True, null=True)),
                ('age_descricaosite', models.CharField(blank=True, max_length=70, null=True)),
                ('age_verificar', models.CharField(blank=True, max_length=1, null=True)),
                ('age_inscricaomunicipal', models.CharField(blank=True, max_length=20, null=True)),
                ('age_markup', models.FloatField(blank=True, null=True)),
                ('aco_codigo', models.IntegerField(blank=True, null=True)),
                ('age_markupliberado', models.FloatField(blank=True, null=True)),
                ('age_codigoprincipal', models.IntegerField(blank=True, null=True)),
                ('age_codigoimportacao', models.IntegerField(blank=True, null=True)),
                ('age_razaosocial', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'verbose_name': 'Agencia',
                'verbose_name_plural': 'Agencias',
                'db_table': 'agencia',
            },
        ),
    ]
