# Generated by Django 5.0.7 on 2024-07-30 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomum', '0009_agencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faturamentosimplificado',
            name='age_codigo',
            field=models.ForeignKey(blank=True, db_column='age_codigo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='incomum.agencia'),
        ),
    ]
