name: Deploy Django Backend DEV

on:
  push:
    branches:
      - sprint  # branch de desenvolvimento
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Copy Files to VPS
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvc --delete --exclude=.env"
          SOURCE: "."
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: ${{ secrets.REMOTE_TARGET_DEV }}
            
      - name: Deploy para VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST_IP }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
              cd ${{ secrets.REMOTE_TARGET_DEV }}
              python3 -m venv venv
              source venv/bin/activate
              git checkout sprint
              
              git pull origin sprint
              pip install -r requirements.txt
              python3 manage.py migrate
              python3 manage.py collectstatic --noinput
              sudo systemctl restart viagemincomum-dev