name: Deploy Django Backend

on:
  push:
    branches:
      - sprint  # ou o branch que você deseja monitorar para deploy
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # ou a versão do Python que você está usando
     
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Write env file
        run: |
          echo "${ENV_DEV}" > .env
      - name: Collect static files
        run: |
          source venv/bin/activate
          python manage.py collectstatic --noinput

      - name: Migrate database
        run: |
          source venv/bin/activate
          python manage.py migrate

      - name: Deploy to Hostinger
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SSH_PASSPHRASE: ${{ secrets.SERVER_SSH_PASSPHRASE }}
          ARGS: "-rltgoDzvc --delete"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: ${{ secrets.REMOTE_TARGET_DEV }}
