name: Deploy Django Backend

on:
  push:
    branches:
      - sprint  # branch de desenvolvimento
      - qa      # branch de staging
      - main    # branch de produção
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SSH INTO SERVER AND DEPLOY
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST_IP }} -p ${{ secrets.REMOTE_PORT }}
          if [ "${{ github.ref }}" == "refs/heads/sprint" ]; then
            cd ${{ secrets.REMOTE_TARGET_DEV }}
            source venv/bin/activate
            git checkout sprint
            echo ${{ secrets.ENV_DEV }} > .env
            git pull origin sprint
            pip install -r requirements.txt
            python manage.py migrate
            sudo systemctl restart viagemincomum-dev
          elif [ "${{ github.ref }}" == "refs/heads/qa" ]; then
            cd ${{ secrets.REMOTE_TARGET_STAGE }}
            source venv/bin/activate
            git checkout qa
            echo ${{ secrets.ENV_STAGE }} > .env
            git pull origin qa
            pip install -r requirements.txt
            python manage.py migrate
            sudo systemctl restart viagemincomum-stage
          elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
            cd ${{ secrets.REMOTE_TARGET_PROD }}
            source venv/bin/activate
            git checkout main
            echo ${{ secrets.ENV_PROD }} > .env
            git pull origin main
            pip install -r requirements.txt
            python manage.py migrate
            sudo systemctl restart viagemincomum-prod
          fi
        env:
          REMOTE_PASSWORD: ${{ secrets.SERVER_SSH_PASSPHRASE }}

          


          
